kind = "web"
previewPath = "/"
title = "FaceUfsc"
version = "1.0.0"
id = "artifacts/faceufsc"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24611

[services.development]
run = "pnpm --filter @workspace/faceufsc run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/faceufsc", "run", "build" ]
publicDir = "artifacts/faceufsc/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24611"
BASE_PATH = "/"
